# Generated by Django 4.0 on 2022-01-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.TextField(null=True, verbose_name='Изображение'),
        ),
    ]
