# Generated by Django 4.0 on 2022-01-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vet', '0004_doctor_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_spec',
            field=models.CharField(default=None, max_length=60, verbose_name='Специальность'),
        ),
    ]
