# Generated by Django 4.0 on 2022-01-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vet', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=60, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ')], max_length=2, verbose_name='День недели')),
                ('sch', models.TextField(null=True, verbose_name='Расписание')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ФИО', to='Vet.doctor')),
            ],
        ),
    ]
