# Generated by Django 4.0 on 2022-01-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vet', '0005_doctor_doc_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': ' врача', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': ' услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vet.doctor', verbose_name='Врач'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doc', 'day')},
        ),
    ]
